version: '3.7'

services:

  wordpress:
    build:
      context: ./misc
      dockerfile: Dockerfile
    image: wooya-wp:php7.3
    restart: always
    container_name: wooya-wp
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.66
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../../../wp-content:/var/www/html/wp-content

  db:
    image: mariadb:10.3
    restart: always
    container_name: database
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wooya
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - backend
    ports:
      - 1025:1025
      - 8025:8025

volumes:

  db_data:

networks:

  backend:
    name: backend
